version: '3'
services:
  node-app:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "5054:5054"
    volumes:
     - .:/app
    environment:
      MONGO_URI: ${MONGO_URL}
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    container_name: my-mongo-vehicles
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
